### ISSUE TITLE
[BassieMusic][v1.3]Can not install the app.

### ISSUE THREAD

**Issue by maaudrana** [bplaat/bassiemusic-android#1]
<h4>Actual Behaviour </h4>
The app can not complete installation process in my device.
<h4>Expected behavior</h4>
Expected that i can successfully install the app.
</h4>
<h4>Step to Reproduce </h4>
<ol>
<li>Download latest version from release page</li>
<li>click the app to install</li>
<li>Click install and if blocked by play protect ,click install any way.</li>
<li> see error</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:v1.3</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/BkKaD9nv6kA">https://youtu.be/BkKaD9nv6kA</a>

**Comment by bplaat** [comment]
I assume you have downloaded the `apk` from GitHub and tried to install it on your device. But that won't work because Google Play Protect prevented that.

This is probably because Google Play Protect thinks that all `apks` downloaded from the internet are viruses. Have you tried to install the app via the Google Play store or to disable Google Play Protect?
You can find it in the Google Play Store [here](https://play.google.com/store/apps/details?id=nl.plaatsoft.bassiemusic).

The source code is open so you can see that it is not a danger, but any way thanks for filing this issue.

**Comment by bplaat** [comment]
I have improved the readme page, now it's more clear how you can download the app.

And I added a few screenshots of the app.

**Comment by maaudrana** [comment]
> I assume you have downloaded the `apk` from GitHub and tried to install it on your device. But that won't work because Google Play Protect prevented that.
> 
> This is probably because Google Play Protect thinks that all `apks` downloaded from the internet are viruses. Have you tried to install the app via the Google Play store or to disable Google Play Protect?
> You can find it in the Google Play Store [here](https://play.google.com/store/apps/details?id=nl.plaatsoft.bassiemusic).
> 
> The source code is open so you can see that it is not a danger, but any way thanks for filing this issue.

No i can install  apk from any source.Cause give the permission  by clicking  "install any way".I tried  with many other app.

**Comment by maaudrana** [comment]
I can not get the latest  apk from playstore.

**Comment by bplaat** [comment]
I don't really know it either. It is probably because I've built the app in a non-standard way via a shell script see `build.sh` this gives normally no problems. It works fine on all the devices I've tested the app on.

That the latest version isn't available your county is strange because in the Netherlands (the county where I live) the latest version (1.3) is just available, so it may take a while before it becomes available in your country.

**Comment by maaudrana** [comment]
Oh i see its now available  in playstore  but don't  know why not working  if i download  apk from release  page.

**Comment by bplaat** [comment]
And have you been able to download and use the app?

**Comment by maaudrana** [comment]
Yes i did.
